#!/bin/sh

WIFI_INTERFACE=en0
WIRED_INTERFACE=en4
DEFAULT_SSID="Digitaino Turbo"
TEMP_LOCATION="/Users/pesqair/.wifi_ssid"


WIFI_STATUS=$(ifconfig $WIFI_INTERFACE | grep status | awk -F' ' '{ print$2 }')

if [[ ("$(ifconfig $WIRED_INTERFACE | grep status | awk -F' ' '{ print$2 }')" = "active" ) ]]
then
	WIRED_STATUS="active"
else
	WIRED_STATUS="disconnected"
fi

echo "------------Network Check RUN------------"
echo $(date)
echo "WIFI_STATUS: $WIFI_STATUS"
echo "WIRED_STATUS: $WIRED_STATUS"


if [[ ("$WIRED_STATUS" = "active" ) && ("$WIFI_STATUS" = "active" ) ]]
then
	networksetup -getairportnetwork $WIFI_INTERFACE | awk -F':' '{ print$2 }' | cut -c 2- > $TEMP_LOCATION
	read WIFI_SSID < $TEMP_LOCATION
	sudo /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport "$WIFI_INTERFACE" -z
	echo "Action: WiFi disconnecting from $WIFI_SSID"
	osascript -e 'display notification "Ethernet connected, disassociating from Wi-Fi network..." with title "Network Status" sound name "Glass.aiff"'
elif [[ ("$WIRED_STATUS" != "active" ) && ("$WIFI_STATUS" != "active" ) ]]; then
	read WIFI_SSID < $TEMP_LOCATION
	if [[ -z "$WIFI_SSID"  ]]; then
		WIFI_SSID=$DEFAULT_SSID
		echo "No wifi_ssid found in $TEMP_LOCATION. Using default_ssid $DEFAULT_SSID"
	fi
	networksetup -setairportnetwork $WIFI_INTERFACE "$WIFI_SSID"
	echo "Action: WiFi connecting to $WIFI_SSID"
	osascript -e 'display notification "Ethernet disconnected, reconnecting to last known Wi-Fi network..." with title "Network Status" sound name "Glass.aiff"'
else
	echo "Action: NO CHANGE"
fi
